version: '3.8'

services:
  db:
    image: postgres:15
    container_name: golabs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: golabs_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: mydb
      DB_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  postgres_data: